site_name: My Blog
site_url: https://woodson-04.github.io/dlf.github.io/

theme:
  name: material
  features:
    - navigation.tabs  # 顶部标签式导航栏
    - navigation.path    # 启用面包屑导航
    - navigation.instant   # 优化交互流畅度（可选）
    - content.code.annotate  # 添加这个特性以支持数学公式
    - navigation.indexes
  palette:
  logo: img/logo.svg       # 导航栏logo路径
  favicon: img/favicon.svg # favicon路径
  
plugins:
  - search  # 默认搜索插件
  #- blog:   # 博客插件配置
      #post_dir: posts

nav: 
# 注意贡献时 - 不可少，且前面空格必须手打，不能tab
  - 主页: index.md
  - 农学:
    - 主页: posts/农学/index.md
    - 植物系统学(PLANT SYSTEMATICS): posts/农学/plant_systematics.md
    - 生物化学(BIOCHEMISTRY): posts/农学/biochemistry.md
  #- 公务员: posts/公务员/index.md
  - 模板: 
    - 主页: posts/模板/index.md
    - PPT: posts/模板/PPT.md
  - 思想感悟: 
    - 主页: posts/思想感悟/index.md
    #- 人际交往: posts/思想感悟/人际交往.md
  - 天文: 
    - 主页: posts/天文/index.md
    - 图片: posts/天文/photos.md
  - 绿色植物百科:
      - 藻类: posts/绿色植物百科/藻类.md
      - 苔藓类: posts/绿色植物百科/苔藓类.md
      - 石松类和蕨类: posts/绿色植物百科/石松类和蕨类.md
      - 裸子植物: posts/绿色植物百科/裸子植物.md
      - 被子植物: posts/绿色植物百科/被子植物.md

markdown_extensions:
  - attr_list  # 允许 Markdown 中添加 HTML 属性（如图片样式）
  - pymdownx.arithmatex:  # 添加数学公式支持
      generic: true       # 使用通用模式（KaTeX）
  - pymdownx.superfences
  - pymdownx.highlight

extra_javascript:
  # 用mathjax显示数学公式
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  # 现有样式
  - stylesheets/custom.css
use_directory_urls: false  # 禁用目录式URL，确保图片路径正确